version: '3.8'
services:

  db:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5434'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "zkCli.sh", "-server", "localhost:2181", "ls", "/"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    env_file:
      - .env
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '9092:9092'

  app:
    build:
      context: .
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    ports:
      - '8000:8000'

volumes:
  pgdata:
