version: '3.8'
services:

  test_db:
    image: postgres:17.2
    env_file:
      - ./tests/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
    restart: on-failure
    networks:
      - applications_test
      
  test_zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    env_file:
      - ./tests/.env
    healthcheck:
      test: ["CMD", "zkCli.sh", "-server", "localhost:2182", "ls", "/"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '2182:2182'
    restart: on-failure
    networks:
      - applications_test

  test_kafka:
    image: confluentinc/cp-kafka:7.8.0
    env_file:
      - ./tests/.env
    depends_on:
      - test_zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9093", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '9093:9093'
    restart: on-failure
    networks:
      - applications_test

  test_app:
    build:
      context: .
    command: >
      sh -c "chmod a+x /app/scripts/*.sh && 
      /app/scripts/run_migrations.sh && 
      /app/scripts/run_pytest.sh"
    depends_on:
      - test_db
      - test_kafka
    env_file:
      - ./tests/.env
    ports:
      - '8001:8001'
    restart: on-failure
    networks:
      - applications_test

networks:
  applications_test:
